# Generated by Django 3.2.7 on 2022-07-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_alter_maintenance_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='payment_date',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
