# Generated by Django 3.2.7 on 2022-07-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_ex_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ex_user',
            name='flat',
            field=models.CharField(default='default', max_length=10),
        ),
        migrations.AddField(
            model_name='ex_user',
            name='society_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
