# Generated by Django 3.2.7 on 2022-07-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0005_complain'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='complain_solution',
            field=models.CharField(default='default', max_length=150),
        ),
    ]
